### ISSUE TITLE
0x2170Ed0880ac9A755fd29B2688956BD959F933F8.

### ISSUE THREAD

**Issue by Nadzir80** [binance-chain/whitepaper#23]
If interpreting this correctly it would be nice if can have this address 0x2170Ed0880ac9A755fd29B2688956BD959F933F8 inside this wallet address
0xaf4942c96C92A8b0B2Ba2Ee32a2a356D091E4a0f

**Comment by Mikazuki21** [comment]
Why

**Comment by spenk1983** [comment]
hi I don't understand the meaning of this email, kindly can you explain to us what it means?‘ Inviato da Posta per Windows 10 Da: Mikazuki21Inviato: mercoledì 28 aprile 2021 08:12A: binance-chain/whitepaperCc: SubscribedOggetto: Re: [binance-chain/whitepaper] 0x2170Ed0880ac9A755fd29B2688956BD959F933F8. (#23) Why—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ny030897** [comment]
> Nếu diễn giải điều này một cách chính xác, sẽ rất tuyệt nếu có thể có địa chỉ này 0x2170Ed0880ac9A755fd29B2688956BD959F933F8 bên trong địa chỉ ví này
> 0xaf4942c96C92A8b0B2Ba2Ee32a2a356D091E4a0f

**Comment by kakakapro123** [comment]
What is this

Vào 4:16, CN, 4 thg 7, 2021 ny030897 ***@***.***> đã viết:

**Comment by Gledis123** [comment]
Why not open
